trigger:
  branches:
    include:
      - master
  tags:
    include:
      - v*

variables:
  eslintConfig: "eslint-config"
  reactApp: "react-app"
  reactAppBasic: "react-app-basic"
  reactAppCommon: "react-app-common"
  reactAppRouterRedux: "react-app-router-redux"
  reactAppRouterReduxAsync: "react-app-router-redux-async"

stages:
  - stage: Build
    pool:
      vmImage: "ubuntu-18.04"
    jobs:
      - job: Package
        steps:
          - task: UseGitVersion@5
            displayName: "Git Version"
            inputs:
              versionSpec: "5.0.0"
              useConfigFile: true
              configFilePath: "$(Build.SourcesDirectory)/GitVersion.yml"
          - task: Yarn@3
            displayName: "Install"
            inputs:
              ProjectDirectory: $(Build.SourcesDirectory)
          - task: Yarn@3
            displayName: "Update version"
            inputs:
              ProjectDirectory: $(Build.SourcesDirectory)
              arguments: "run version $(Build.BuildNumber)"
          - template: pack-template.yml
            parameters:
              package: $(eslintConfig)
          - template: pack-template.yml
            parameters:
              package: $(reactApp)
          - template: pack-template.yml
            parameters:
              package: $(reactAppBasic)
          - template: pack-template.yml
            parameters:
              package: $(reactAppCommon)
          - template: pack-template.yml
            parameters:
              package: $(reactAppRouterRedux)
          - template: pack-template.yml
            parameters:
              package: $(reactAppRouterReduxAsync)
  - stage: Deploy
    dependsOn: Build
    condition: and(succeeded(), contains(variables['Build.Reason'], 'PullRequest'))
    pool:
      vmImage: "ubuntu-18.04"
    jobs:
      - deployment: DevBuild
        environment: "dev-builds"
        strategy:
          runOnce:
            deploy:
              steps:
                - template: deploy-dev-template.yml
                  parameters:
                    package: $(eslintConfig)
                - template: deploy-dev-template.yml
                  parameters:
                    package: $(reactApp)
                - template: deploy-dev-template.yml
                  parameters:
                    package: $(reactAppBasic)
                - template: deploy-dev-template.yml
                  parameters:
                    package: $(reactAppCommon)
                - template: deploy-dev-template.yml
                  parameters:
                    package: $(reactAppRouterRedux)
                - template: deploy-dev-template.yml
                  parameters:
                    package: $(reactAppRouterReduxAsync)
  - stage: Release
    dependsOn: Build
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'tags/v'))
    pool:
      vmImage: "ubuntu-18.04"
    jobs:
      - deployment: Public
        environment: "public"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: GitHubRelease@1
                  displayName: "Update GitHub release"
                  inputs:
                    gitHubConnection: "mocoding-software"
                    repositoryName: "mocoding-software/react-app"
                    action: edit
                    tag: "v$(Build.BuildNumber)"
                    assets: "$(Pipeline.Workspace)/**/*.tgz"
                    assetUploadMode: replace
                - template: deploy-prod-template.yml
                  parameters:
                    package: $(eslintConfig)
                - template: deploy-prod-template.yml
                  parameters:
                    package: $(reactApp)
                - template: deploy-prod-template.yml
                  parameters:
                    package: $(reactAppBasic)
                - template: deploy-prod-template.yml
                  parameters:
                    package: $(reactAppCommon)
                - template: deploy-prod-template.yml
                  parameters:
                    package: $(reactAppRouterRedux)
                - template: deploy-prod-template.yml
                  parameters:
                    package: $(reactAppRouterReduxAsync)                
