# File: deploy-dev-template.yml
parameters:
  - name: package
    type: string
    default: ""
steps:
  - task: Npm@1
    displayName: "${{ parameters.package }} - Publish to npm (dev-builds)"
    inputs:
      command: "custom"
      customCommand: "publish $(Pipeline.Workspace)/npm/${{ parameters.package }}-$(Build.BuildNumber).tgz"
      customRegistry: "useFeed"
      customFeed: "da7703d4-fb22-4933-b869-83f4264b7b84/e1336e71-3540-4a0c-830c-639112685b07"
