# File: build-and-pack-template.yml
parameters:
  - name: package
    type: string
    default: ""
steps:
  - task: Yarn@3
    displayName: "${{ parameters.package }} - Update version"
    inputs:
      projectDirectory: "$(Build.SourcesDirectory)/packages/${{ parameters.package }}"
      arguments: "version --new-version $(Build.BuildNumber) --no-git-tag-version"
  - task: Yarn@3
    displayName: "${{ parameters.package }} - Pack"
    condition:
    inputs:
      arguments: "pack --filename $(Build.StagingDirectory)/${{ parameters.package }}-$(Build.BuilderNumber).tgz"
      projectDirectory: "$(Build.SourcesDirectory)/packages/${{ parameters.package }}"
  - task: PublishBuildArtifacts@1
    displayName: "${{ parameters.package }} - Publish ${{ parameters.package }}"
    inputs:
      PathtoPublish: "$(Build.StagingDirectory)/${{ parameters.package }}-$(Build.BuilderNumber).tgz"
      ArtifactName: npm-${{ parameters.package }}
