# File: build-and-pack-template.yml
parameters:
  - name: package
    type: string
    default: ""
steps:
  - task: Yarn@3
    displayName: "${{ parameters.package }} - Pack"
    condition:
    inputs:
      arguments: "pack --filename $(Build.StagingDirectory)/${{ parameters.package }}-$(Build.BuildNumber).tgz"
      projectDirectory: "$(Build.SourcesDirectory)/packages/${{ parameters.package }}"
  - task: PublishBuildArtifacts@1
    displayName: "${{ parameters.package }} - Publish"
    inputs:
      PathtoPublish: "$(Build.StagingDirectory)/${{ parameters.package }}-$(Build.BuildNumber).tgz"
      ArtifactName: npm-${{ parameters.package }}
